---
logging:
  level: INFO
  loggers:
    com.authservice: DEBUG
database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: 2903e3ac75c5234f
  url: jdbc:postgresql://srv-captain--movielib-db:5432/movie_library
  properties:
    charSet: UTF-8
  maxWaitForConnection: 3s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: true
  checkConnectionOnBorrow: true
  evictionInterval: 10s
  minIdleTime: 1 minute
flyway:
  baselineOnMigrate: true
  validateOnMigrate: true
  locations:
  - filesystem:src/main/java/com/authservice/db/migration
  baseLineVersion: 1
rabbitmq:
  host: srv-captain--movielib-mq
  port: 5672
  username: guest
  password: guest